---
- name: config | Configuring Cassandra
  template:
    src: "etc/cassandra/cassandra.yaml.j2"
    dest: "{{ cassandra_root_dir }}/cassandra.yaml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart cassandra"

- name: "config | Restarting cassandra"
  service:
    name: "cassandra"
    state: "restarted"
