---
- name: config | Configuring Cassandra
  template:
    src: "etc/cassandra/cassandra.yaml.j2"
    dest: "{{ cassandra_root_dir }}/cassandra.yaml"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart cassandra"

- name: "config | Restarting cassandra"
  service:
    name: "cassandra"
    state: "restarted"

- name: config | Configuring Cassandra Datacenter
  template:
    src: "etc/cassandra/cassandra-rackdc.properties.j2"
    dest: "{{ cassandra_root_dir }}/cassandra-rackdc.properties"
    owner: "root"
    group: "root"
    mode: 0644
  notify: "restart cassandra"

- name: Wait for server autostart
  wait_for: path=/var/log/cassandra/system.log search_regex="Starting listening for CQL clients"
