- hosts: cassandra-cluster-nodes
  become: true
  vars:
    cassandra_cluster_setup: true
    cassandra_config: true
    cassandra_listen_interface: eth0
    cassandra_snitch: GossipingPropertyFileSnitch
    pri_domain_name: 'hub.subut.ai'
  roles:
    - role: ansible-oracle-java8
    - role: ansible-cassandra
  tasks:
