- hosts: cassandra-cluster-nodes
  become: true
  vars:
    cassandra_cluster_setup: true
    cassandra_config: true
    cassandra_listen_interface: enp0s8
    cassandra_snitch: SimpleSnitch # SimpleSnitch | Ec2MultiRegionSnitch etc..
    pri_domain_name: 'hub.subut.ai'
  roles:
    - role: ansible-oracle-java8
    - role: ansible-cassandra
  tasks:
