---
- name: Install MariaDB server, python-mysqldb and rsync packages
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - rsync
    - python-mysqldb

# - name: Install Percona tool packages
#  yum: name={{ item }} state=present
#  with_items:
#    - percona-xtrabackup
#    - socat

# - name: Install MySQL-python
#  apt: name=python-mysqldb state=present
