---

#- name: Create conf directory
#  file: path=/etc/mysql/conf.d state=directory mode=0755

- name: Add galera configuration
  template: src=server.cnf.j2 dest=/etc/mysql/conf.d/galera.cnf
    owner=root group=root mode=0644
  notify: Restart MariaDB Galera cluster
